name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test-coverage
      - uses: coverallsapp/github-action@v2
